### ISSUE TITLE
Publish dotty 0.19 version to maven central

### ISSUE THREAD

**Issue by debian0501** [factor10/intent#40]
Currently I only find a version for dotty 0.18 on maven central (https://search.maven.org/artifact/com.factor10/intent_0.18/0.1.0/jar). Can you also publish the 0.19 version? Or on which repository can I find it?

**Comment by provegard** [comment]
We'll fix. Thanks for the reminder!

**Comment by eliasson** [comment]
Version 0.2.0 is now published (which requires 0.19 of dotty), as well as version 0.3.0 using 0.20 of dotty.
Enjoy!
